name: "Terraform Plan"

on:
  push:
    branches:
      - feature

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-24.04

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Terraform Init
        working-directory: ./environment/dev
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=dev/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}"

      - name: Terraform Validate
        working-directory: ./environment/dev
        run: terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ./environment/dev
        run: terraform plan -no-color
