name: "Deploy"

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      destroy:
        description: "Run Terraform destroy plan?"
        required: true
        default: false
        type: boolean

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-24.04

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Terraform Init
        working-directory: ./environment/dev
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=dev/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_DEFAULT_REGION }}"

      - name: Terraform Validate
        working-directory: ./environment/dev
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request' || github.event.inputs.destroy != 'true'
        working-directory: ./environment/dev
        run: terraform plan -no-color

      - name: Terraform Destroy Plan
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true'
        working-directory: ./environment/dev
        run: terraform plan -destroy -no-color